module.exports = [
  'react',
  'react-dom',
  'react-tap-event-plugin',
  'redux',
  'react-redux',
  'causality-redux',
  'react-causality-redux',
  'react-causality-redux-router',
  'react-router-dom',
  'history',
  'material-ui',
  'redux-logger',
  'redux-thunk',
  'whatwg-fetch',
  'object.assign',
  'es6-promise',
  'array.from'
]
