module.exports = {
  'useCausalityRedux': true,
  'useMaterialUI': true,
  'useReactRouterWithTimeTravel': false,
  'useReactRouterWithoutTimeTravel': true,
  'sourceDir': 'src',
  'reactComponentsDirectory': 'react-components',
  'useCSSModules': 2,
  'noCSSModulesName': 'no_css_modules',
  'useLess': true,
  'useSass': true,
  'useCss': true,
  'useLessInjections': true,
  'useSassInjections': true,
  'useCssInjections': true,
  'urlLoaderLimit': '32000',
  'useDllLibraryForProduction': false,
  'useWatch': false,
  'strDllModule': '',
  'buildDir': 'dist',
  'buildScriptDir': 'scripts',
  'buildCSSDir': 'css',
  'bundleName': 'bundle',
  'assetsDirectory': 'assets',
  'dllDir': 'devdll',
  'dllBundleName': 'dllbundle',
  'htmlOutputFileName': 'index.html',
  'htmlTemplate': 'index.ejs',
  'htmlDevTemplate': 'index.dev.ejs',
  'strUrlLoaderExtensions': '.png, .jpeg, .jpg, .gif',
  'strResolveExtensions': '.js, .jsx, .json, .sass, .scss, .css, .less',
  'webpackPath': './node_modules/webpack/bin/webpack',
  'mochaPath': './node_modules/mocha/bin/_mocha',
  'reactRootId': 'reactroot',
  'useTypeScript': false,
  'devProxyList': '',
  'devProxyURL': '',
  'devProxyPort': '',
  'devProxyServerPathName': '',
  'prodProxyList': '',
  'prodProxyURL': '',
  'prodProxyPort': '',
  'prodProxyServerPathName': '',
  'isProgressiveWebApp': false,
  'strProgressiveWebAppCacheFiles': '',
  'strLibraryFiles': 'core-js/es6/map\ncore-js/es6/set\ncore-js/es6/promise\ncore-js/fn/object/assign\ncore-js/fn/array/from\nisomorphic-fetch\nredux-logger\nredux-thunk'
}
